ToDo/ToDo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('my_todo.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

ToDo/my_todo/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('todo/', views.ToDoList.as_view(), name="list_todo"),
    path('new_todo/', views.NewTodo.as_view(), name='new_todo'),
    path('<int:pk>/', views.ToDoDetail.as_view(), name='detail_todo'),
    path('<int:pk>/delete/', views.DeleteToDo.as_view(), name='delete_todo'),
    path('<int:pk>/edit/', views.UpdateToDo.as_view(), name='update_todo'),
    # Auth
    # admin: Denis, password: qwe
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('logined/', views.LoginUser.as_view(), name='logined'),
    path('logout/', LogoutView.as_view(), name='logout')
]

ToDo/my_todo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse


class ToDo(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='Имя')
    title = models.CharField(max_length=200)
    content = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Заметка'
        verbose_name_plural = 'Заметки'
        ordering = ['-date_created']

    def get_absolute_url(self):
        return reverse('detail_todo', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

ToDo/my_todo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import ToDo


class NewToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['title', 'content']


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

ToDo/my_todo/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from .models import ToDo
from .forms import NewToDoForm, RegisterForm, LoginForm


def index(request):
    return render(request, 'my_todo/startpage.html')


class ToDoList(ListView):
    paginate_by = 5
    model = ToDo
    template_name = 'my_todo/todo_list.html'
    context_object_name = 'todos'

    def get_queryset(self):
        return ToDo.objects.filter(author=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['form'] = NewToDoForm()
        return context


class ToDoDetail(LoginRequiredMixin, DetailView):
    model = ToDo
    context_object_name = 'todo'
    template_name = 'my_todo/detail_todo.html'


class NewTodo(LoginRequiredMixin, CreateView):
    form_class = NewToDoForm
    template_name = 'my_todo/new_todo.html'

    def form_valid(self, form):
        todo = form.save(commit=False)
        todo.author = self.request.user
        todo.save()
        return redirect('detail_todo', todo.pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['new'] = True
        return context


class DeleteToDo(LoginRequiredMixin, DeleteView):
    model = ToDo
    template_name = 'my_todo/detail_todo.html'
    success_url = reverse_lazy('list_todo')


class UpdateToDo(LoginRequiredMixin, UpdateView):
    model = ToDo
    form_class = NewToDoForm
    template_name = 'my_todo/detail_todo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['edit'] = True
        return context


class RegisterUser(CreateView):
    form_class = RegisterForm
    template_name = 'my_todo/register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("index")


class LoginUser(LoginView):
    form_class = LoginForm
    template_name = 'my_todo/logined.html'

ToDo/my_todo/templates/my_todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{% static "logo.png" %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block css %}
    {% endblock css %}
    <title>
      {% block title %}
        ToDo Заметки
      {% endblock title %}
    </title>
  </head>
  <body>
    <nav class="nav">
      {% if user.is_authenticated %}
        <div class="nav-text2">
          <a href="{% url 'list_todo' %}">
            <img src="{% static 'logo.png' %}" alt="ToDo" width="50" height="50">
          </a>
          <a href="{% url 'list_todo' %}" class="nav-text2">Заметки</a>
        </div>
      {% else %}
        <div class="nav-text2">
          <a href="{% url 'index' %}">
            <img src="{% static 'logo.png' %}" alt="ToDo" width="50" height="50">
          </a>
          <a href="{% url 'index' %}" class="nav-text2">Заметки</a>
        {% endif %}
      </div>
      <div class="nav-text">
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'new_todo' %}">Добавить заметку</a> |
          <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
        {% else %}
          <a class="nav-link" href="{% url 'logined' %}">Войти</a> |
          <a class="nav-link" href="{% url 'register' %}">Зарегистрироваться</a>
        {% endif %}
      </div>
    </nav>
    <div class="content">
      {% block content %}
      {% endblock content %}
    </div>
    <footer class="footer">
      <div class="footer-text">
        <a class="footer-link" href="https://github.com/dend0s">Об авторе</a>
      </div>
    </footer>
  </body>
</html>

ToDo/my_todo/templates/my_todo/detail_todo.html
{% extends 'my_todo/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'new_detail_style.css' %}">
{% endblock css %}
{% block title %}
    Заметка
{% endblock title %}
{% block content %}
    {% if edit %}
        <form method="post" action="{% url 'update_todo' todo.pk %}" class="decor">
            {% csrf_token %}
            <div class="form-inner">
                <h3>Редактирование заметки</h3>
                <input type="text" name="title" required id="id_title" value={{ todo.title }}>
                <textarea name="content" id="id_content" rows="3">{{todo.content}}</textarea>
                <input type="submit" value="Сохранить">
            </div>
        </form>
    {% else %}
        <div class="todo_detail">
            <div class="todo_title">{{ todo.title }}</div>
            <div class="todo_content">{{ todo.content }}</div>
            <div class="todo_time">Дата создания: {{ todo.date_created }}</div>
            <div class="todo_buttons">
                <button class="button_todo" type="submit">
                    <a class="button_link_todo" href="{% url 'update_todo' todo.pk %}">Изменить</a>
                </button>
            </div>
            {# Delete ToDo #}
            <div class="todo_buttons">
                <form method="post" action="{% url 'delete_todo' todo.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="button_todo">Удалить</button>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock content %}

ToDo/my_todo/templates/my_todo/logined.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'login_style.css' %}">
    <link rel="icon" type="image/png" href="{% static "logo.png" %}">

    <title>Авторизация</title>
</head>
<body>
<form method="post" class="ui-form">
    {% csrf_token %}
    <h3><img src="{% static 'logo.png'%}" alt="ToDo" width="30" height="30">&nbsp;Войти на сайт</h3>
    <div class="form-row">
    <input type="text" name="username" required id="id_username"><label for="id_username">Имя пользователя</label>
    </div>
    <div class="form-row">
    <input type="password" name="password" required id="id_password"><label for="id_password">Пароль</label>
    </div>
    <p><input type="submit" value="Войти"></p>
    <p class="link"><a href={% url 'register' %}>Зарегистрироваться</a></p>
</form>  
</body>
</html>

ToDo/my_todo/templates/my_todo/new_todo.html
{% extends 'my_todo/base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'new_detail_style.css' %}"> {% endblock css %}
{% block title %}Новая заметка{% endblock title %}
{% block content %}
    <form method="post" class="decor">
        {% csrf_token %}
        <div class="form-inner">
        <h3>Новая заметка</h3>
        <input type="text" name="title" placeholder="Заголовок">
        <textarea placeholder="Текст..." rows="3" name="content"></textarea>
        <input type="submit" value="Добавить">
        </div>
    </form>
{% endblock content %}

ToDo/my_todo/templates/my_todo/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    <link rel="icon" type="image/png" href="{% static "logo.png" %}">
    <link rel="stylesheet" href="{% static 'login_style.css' %}">
</head>
<body>
<form method="post" class="ui-form">
    {% csrf_token %}
    <h3><img src="{% static 'logo.png'%}" alt="ToDo" width="30" height="30">&nbsp;Регистрация</h3>
    <div class="form-row">
    <input type="text" name="username" required id="id_username"><label for="id_username">Имя пользователя</label>
    </div>
    <div class="form-row">
    <input type="password" name="password1" required id="id_password1"><label for="id_password1">Пароль</label>
    </div>
    <div class="form-row">
    <input type="password" name="password2" required id="id_password2"><label for="id_password2">Подтверждение пароля</label>
    </div>
    <p><input type="submit" value="Зарегистрироваться"></p>
    <p class="link"><a href={% url 'logined' %}>Войти</a></p>
</form>
</body>
</html>

ToDo/my_todo/templates/my_todo/startpage.html
{% extends 'my_todo/base.html' %}
{% block title %}ToDo Заметки{% endblock title %}
{% block content %}
    <div class="start-text">
        {% if user.is_authenticated %}
            Привет, {{ user }}!
            <br>
            <a class="link" href="{% url 'list_todo' %}">Просмотреть заметки</a>
        {% else %}
            Для просмотра заметок необходимо <a class="link" href="{% url 'logined' %}">войти</a> или
            <a class="link" href="{% url 'register' %}">зарегистрироваться</a>
            </div>
        {% endif %}
{% endblock content %}

ToDo/my_todo/templates/my_todo/todo_list.html
{% extends 'my_todo/base.html' %}
{% block title %}Заметки{% endblock title %}

{% block content %}
        {% if todos %}
            <div class="todo_header">Список заметок</div>
            <ul class="ul">
                {% for t in todos %}
                    <li class="li"><a class="link" href="{% url 'detail_todo' t.pk %}">{{ t.title }}</a></li>
                    <p>{{ t.content|truncatewords:10}}</p>
                {% endfor %}
            </ul>
            {% if page_obj.has_other_pages %}
        <div class="pag"> 
            <ul class="page">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;
                        </a></li>
                {% else %}
                    <li><a>&laquo;
                     </a></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li><b>{{ i }} </b>
                        </li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">
                        &raquo;</a></li>
                {% else %}
                    <li ><a>
                        &raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
        {% else %}
            <div class="start-text">
            Список заметок пуст
            <br>
            <button class="button" type="submit"><a class="button-link" href="{% url 'new_todo' %}">Добавить заметку</a></button>
            </div>
        {% endif %}
        <div class="plus"><a class="plus-link" href="{% url 'new_todo'%}">+</a></div>
{% endblock content %}